# Setup
title:               Ajit Marshall
name:                Ajit
tagline:             Live the Adventure,don't work for money let money work for you
description:         I am a normal soul who loves to tavel, code and read, and wonder about how things work and also a Tech Intern at,<a href="https://www.Vajro.com">Vajro</a>. We built apps for
                     ecommerce industry,my love for coding started at <a href="https://www.wisilica.com">wisilica</a>which are developing for Internet of Things platform.'

url:                 http://www.ajitmarshall.com
# url:                 http://localhost:4000

paginate:            5

github:
  repo:              https://github.com/ajit92

twitter:
  username: ajit_marshall

google_analytics:
 token:             UA-80560343-1

skcript:
  main:              https://www.skcript.com
  blog:              https://blog.skcript.com
  shrink:            https://www.skcript.com/shrink
  allt:              https://allt.in

About/contact
author:
  name:              Ajit Marshall
  twitter:           https://twitter.com/ajit_marshall
  email:             ajit@Vajro.com

# Permalinks
permalink:           pretty

# Custom vars
version:             1.0.0
